#!/usr/bin/env bash
# Displays during loop:
# 4th iteration: "bad luck from China"
# 8th iteration: "bad luck from Japan"
# 17th iteration: "bad luck from Italy"

cnt=1

while [ $cnt -le 20 ]
do
echo "$cnt"
case $cnt in
"4") echo "bad luck from China";;
"9") echo "bad luck from Japan";;
"17") echo "bad luck from Italy";;
esac
(( cnt++ ))
done
