#!/usr/bin/env bash
# Displays the contents of the current directory in list format
# Only displays the part of the name after first dash

list=$(ls)
for a in $list; do
echo "$a" | cut -d '-' -f2
done
