#!/usr/bin/env bash
# Fixes web server to run nginx as user to listen to port 8080.

sed -i "s/#usr www-data/user nginx/" /etc/nginx/nginx.cof
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf

sudo -u nginx service nginx start
